dist: bionic

language: minimal

before_install:
# Install and set up LXD. LXD is used to build the snap.
- sudo apt remove -y --purge lxd lxd-client
- sudo snap install lxd
- sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
- sudo lxd waitready;
- sudo lxd init --auto;
- sudo usermod -a -G lxd travis;
# Install other build dependencies
- sudo snap install charm --classic
- sudo apt-get install -y build-essential flake8

install:
# Workaround for https://github.com/juju/charm-tools/issues/532
- git config --global --unset protocol.version
# Lint check for charm code
- make lint
# Build charm
- sudo su travis -c make

