dist: bionic

language: minimal

before_install:
- sudo apt-get install -y build-essential flake8

install:
- make lint


deploy:
- provider: script
  script: bash charm/deploy.bash
  on:
    branch: master
